messenger4j:
  appSecret: '980e058f85c11dbea4d4b600ffd34719'
  verifyToken : 'message'
  pageAccessToken: 'EAAFVJdz6WecBAPlrgQaFIPS4nTjOQ3ZACvhLffMvVfADI75ZCpoyBjwfcE9ac2YFdCZCYCcy9ic8rhYc5nGpeAG8O68lv5JQOmkBwxwuwxQMXf21z83k6BHzCFiqKhiZChvdbTfkWpltIls7kWnvEYnEvVwpJ3GzWcGehLtDVwZDZD'

logging:
  level:
    com:
      github:
        messenger4j: INFO
server:
    port: '8082'





